version: "3"
services:

# POSTGRES 
 postgres:
  image: postgres:12.4
  restart: always
  container_name: postgres
  networks:
   - kong
  environment:
   - POSTGRES_USER=kong
   - POSTGRES_DB=kong
   - POSTGRES_PASSWORD=kong
   - POSTGRES_HOST_AUTH_METHOD=trust
   - POSTGRES_LOG_CONNECTIONS=on
   - POSTGRES_SSL_MIN_PROTOCOL_VERSION='TLSv1.1'

 cassandra:
  image: cassandra:latest
  container_name: cassandra
  networks:
   - kong
