version: "3"
services:

 kong-ent-bootstrap:
  image: ${KONG_IMAGE}
  container_name: kong-ent-bootstrap
  networks:
   - kong
  restart: on-failure
  command: "kong migrations bootstrap"
  environment:
   - KONG_LICENSE_DATA=${KONG_LICENSE_DATA}
   - KONG_PASSWORD=admin
   - KONG_LOG_LEVEL=debug
   - KONG_VITALS=on

 kong-ent:
   image: ${KONG_IMAGE} #  
   container_name: kong-ent
   networks:
    - kong
   restart: always
   command: "kong start --run-migrations" 
   volumes:
    - ../cert:/tmp/cert
   ports:
    - 8000:8000
    - 8001:8001
    - 8002:8002
    - 8003:8003
    - 8004:8004
    - 8443:8443
    - 8444:8444
    - 8445:8445
    - 8446:8446
    - 8447:8447
   environment:
#   - KONG_ENFORCE_RBAC=on
#   - KONG_ADMIN_GUI_AUTH=basic-auth
#   - KONG_ADMIN_GUI_SESSION_CONF={"secret":"secret","storage":"kong","cookie_secure":false}
    - KONG_PASSWORD=admin
    - KONG_AUDIT_LOG=on
    - KONG_LOG_LEVEL=debug 
    - KONG_PORTAL_GUI_PROTOCOL=http
    - KONG_PORTAL=on
    - KONG_PORTAL_AUTH=basic-auth
    - KONG_LICENSE_DATA=${KONG_LICENSE_DATA}
    - KONG_VITALS=on
    - KONG_PROXY_ACCESS_LOG=/dev/stdout
    - KONG_ADMIN_ACCESS_LOG=/dev/stdout
    - KONG_PROXY_ERROR_LOG=/dev/stderr
    - KONG_ADMIN_ERROR_LOG=/dev/stderr
    - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl
    - KONG_STATUS_LISTEN=0.0.0.0:8100
    - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    - KONG_ADMIN_GUI_LISTEN=0.0.0.0:8002, 0.0.0.0:8445 ssl
    - KONG_PORTAL_GUI_LISTEN=0.0.0.0:8003, 0.0.0.0:8446 ssl
    - KONG_PORTAL_SESSION_CONF={"storage":"kong","cookie_name":"portal_session","secret":"super-secret","cookie_secure":false}
    - KONG_PORTAL_API_LISTEN=0.0.0.0:8004, 0.0.0.0:8447 ssl
    # - KONG_PLUGINSERVER_NAMES=js
    # - KONG_PLUGINSERVER_JS_SOCKET=/usr/local/kong/js_pluginserver.sock
    # - KONG_PLUGINSERVER_JS_START_CMD=/usr/bin/kong-js-pluginserver -v --plugins-directory /usr/local/kong/js-plugins
    # - KONG_PLUGINSERVER_JS_QUERY_CMD=/usr/bin/kong-js-pluginserver --plugins-directory /usr/local/kong/js-plugins --dump-all-plugins
    # - KONG_PLUGINS=bundled,js-hello,js-censor


 kong-cp:
   image: ${KONG_IMAGE} #  
   networks:
    - kong
   restart: always
   command: "kong start --run-migrations" 
   volumes:
    - ../cert:/tmp/cert
   ports:
    - 8001:8001
    - 8002:8002
    - 8003:8003
    - 8004:8004
    - 8444:8444
    - 8445:8445
    - 8446:8446
    - 8447:8447
   environment:
#   - KONG_ENFORCE_RBAC=on
#   - KONG_ADMIN_GUI_AUTH=basic-auth
#   - KONG_ADMIN_GUI_SESSION_CONF={"secret":"secret","storage":"kong","cookie_secure":false}
    - KONG_PASSWORD=admin
    - KONG_AUDIT_LOG=on
    - KONG_LOG_LEVEL=debug 
    - KONG_PORTAL_GUI_PROTOCOL=http
    - KONG_PORTAL=on
    - KONG_PORTAL_AUTH=basic-auth
    - KONG_LICENSE_DATA=${KONG_LICENSE_DATA}
    - KONG_VITALS=on
    - KONG_PROXY_ACCESS_LOG=/dev/stdout
    - KONG_ADMIN_ACCESS_LOG=/dev/stdout
    - KONG_PROXY_ERROR_LOG=/dev/stderr
    - KONG_ADMIN_ERROR_LOG=/dev/stderr
    - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl
    - KONG_STATUS_LISTEN=0.0.0.0:8100
    - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    - KONG_ADMIN_GUI_LISTEN=0.0.0.0:8002, 0.0.0.0:8445 ssl
    - KONG_PORTAL_GUI_LISTEN=0.0.0.0:8003, 0.0.0.0:8446 ssl
    - KONG_PORTAL_SESSION_CONF={"storage":"kong","cookie_name":"portal_session","secret":"super-secret","cookie_secure":false}
    - KONG_PORTAL_API_LISTEN=0.0.0.0:8004, 0.0.0.0:8447 ssl

 kong-dbless:
   image: ${KONG_IMAGE} #  
   networks:
    - kong
   restart: always
   command: "kong start --run-migrations" 
   volumes:
    - ../cert:/tmp/cert
   ports:
    - 8000
    - 8001
    - 8443
    - 8100
   environment:
    - KONG_LOG_LEVEL=debug 
    - KONG_LICENSE_DATA=${KONG_LICENSE_DATA}
    - KONG_VITALS=on
    - KONG_DATABASE=off
    - KONG_PROXY_ACCESS_LOG=/dev/stdout
    - KONG_ADMIN_ACCESS_LOG=/dev/stdout
    - KONG_PROXY_ERROR_LOG=/dev/stderr
    - KONG_ADMIN_ERROR_LOG=/dev/stderr
    - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl
    - KONG_STATUS_LISTEN=0.0.0.0:8100

networks:
  kong:
    ipam:
      driver: default
      config: 
        - subnet: 10.0.0.0/24 
